# Generated by Django 6.0.2 on 2026-02-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0004_alter_shop_options_alter_shopmembership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozon_reports', to='shops.shop')),
            ],
            options={
                'verbose_name': 'отчет Ozon',
                'verbose_name_plural': 'отчеты Ozon',
                'unique_together': {('shop', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OzonSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ok', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='ozon.ozonreport')),
            ],
            options={
                'verbose_name': 'лог синхронизации Ozon',
                'verbose_name_plural': 'логи синхронизации Ozon',
            },
        ),
        migrations.CreateModel(
            name='OzonReportColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('data_type', models.CharField(default='text', max_length=32)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='ozon.ozonreport')),
            ],
            options={
                'verbose_name': 'колонка отчета Ozon',
                'verbose_name_plural': 'колонки отчета Ozon',
                'ordering': ['order', 'id'],
                'unique_together': {('report', 'key')},
            },
        ),
        migrations.CreateModel(
            name='OzonReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(max_length=128)),
                ('sort_key', models.CharField(blank=True, default='', max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ozon.ozonreport')),
            ],
            options={
                'verbose_name': 'строка отчета Ozon',
                'verbose_name_plural': 'строки отчета Ozon',
                'ordering': ['sort_key', 'row_key'],
                'unique_together': {('report', 'row_key')},
            },
        ),
    ]
