# Generated by Django 6.0.2 on 2026-02-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0001_initial'),
        ('shops', '0004_alter_shop_options_alter_shopmembership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonClusterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('cluster_id', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozon_cluster_slots', to='shops.shop')),
            ],
            options={
                'verbose_name': 'слот кластера Ozon',
                'verbose_name_plural': 'слоты кластеров Ozon',
                'unique_together': {('shop', 'code')},
            },
        ),
    ]
