# Generated by Django 6.0.2 on 2026-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='token',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
