# Generated by Django 6.0.2 on 2026-02-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
        migrations.AlterModelOptions(
            name='shopmembership',
            options={'ordering': ['shop', 'user'], 'verbose_name': 'сотрудник магазина', 'verbose_name_plural': 'сотрудники магазинов'},
        ),
        migrations.AddField(
            model_name='shop',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Client-Id'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='marketplace',
            field=models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Яндекс Маркет'), ('other', 'Другое')], default='ozon', max_length=40, verbose_name='Маркетплейс'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='token',
            field=models.CharField(max_length=40, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='can_edit_shop',
            field=models.BooleanField(default=False, verbose_name='Право редактировать магазин'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='can_manage_staff',
            field=models.BooleanField(default=False, verbose_name='Право управлять персоналом'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='can_view_stats',
            field=models.BooleanField(default=True, verbose_name='Доступ к статистике'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
