# Generated by Django 6.0.2 on 2026-02-20 11:56

import account.models
from django.db import migrations, models
from django.db.models import Q


def populate_email_from_username(apps, schema_editor):
    User = apps.get_model("account", "User")
    users = User.objects.filter(Q(email__isnull=True) | Q(email=""))
    for user in users:
        if getattr(user, "username", None):
            user.email = f"{user.username}@example.local".lower()
        else:
            user.email = f"user{user.pk}@example.local"
        user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_email_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
        migrations.RunPython(populate_email_from_username, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
    ]
