# Generated by Django 6.0.2 on 2026-02-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='marketplace',
            field=models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Yandex Market'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
